spring.application.name=Auth_project

# il s'agit de connecter sa base de donner ici


spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/Auth
spring.datasource.username=root
spring.datasource.password=09152T049t@
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true


